addSbtPlugin("org.lyranthe.sbt"    % "partial-unification" % "1.1.2")
addCompilerPlugin("org.spire-math" %% "kind-projector"     % "0.9.7")
addSbtPlugin("io.spray"            % "sbt-revolver"        % "0.9.1")
addSbtPlugin("io.get-coursier"     % "sbt-coursier"        % "1.0.3")
addSbtPlugin("com.lucidchart"      % "sbt-scalafmt"        % "1.15")
